# Generated by Django 5.0.6 on 2024-06-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
