# Generated by Django 5.0.6 on 2024-06-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A', '0003_kelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('preparing_time', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('final_price', models.CharField(max_length=100)),
            ],
        ),
    ]
